### ISSUE TITLE
Building caused issue

### ISSUE THREAD

**Issue by soulspark666** [UsergeTeam/Userge#12]
Tried to build via heroku deployment. Gave all the required values and some non required ones too. but its crashing!
```
2020-05-05T06:59:49.518591+00:00 heroku[worker.1]: State changed from starting to up
2020-05-05T06:59:51.671448+00:00 app[worker.1]: [05-May-20 06:59:51 - INFO] - userge.config - Creating Download Path...
2020-05-05T06:59:51.671609+00:00 app[worker.1]: [05-May-20 06:59:51 - INFO] - userge.config - Checking Heroku App...
2020-05-05T06:59:51.820908+00:00 app[worker.1]: [05-May-20 06:59:51 - INFO] - userge.config - Heroku App : teledrivedow Found...
2020-05-05T06:59:51.821134+00:00 app[worker.1]: [05-May-20 06:59:51 - INFO] - userge.config - Cloning Heroku GIT...
2020-05-05T06:59:52.229095+00:00 app[worker.1]: [05-May-20 06:59:52 - INFO] - userge.config - Creating BIN...
2020-05-05T06:59:52.229249+00:00 app[worker.1]: [05-May-20 06:59:52 - INFO] - userge.config - Downloading BINs...
2020-05-05T06:59:52.556678+00:00 app[worker.1]: [05-May-20 06:59:52 - INFO] - userge.core._database.db - $$$>>> __Connecting to Database...__ <<<$$$
2020-05-05T07:00:22.838054+00:00 app[worker.1]: Traceback (most recent call last):
2020-05-05T07:00:22.838070+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 184, in _run_module_as_main
2020-05-05T07:00:22.838415+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2020-05-05T07:00:22.838434+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 143, in _get_module_details
2020-05-05T07:00:22.838674+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2020-05-05T07:00:22.838696+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 110, in _get_module_details
2020-05-05T07:00:22.838909+00:00 app[worker.1]:     __import__(pkg_name)
2020-05-05T07:00:22.838912+00:00 app[worker.1]:   File "/app/userge/__init__.py", line 13, in <module>
2020-05-05T07:00:22.839081+00:00 app[worker.1]:     from userge.core import (
2020-05-05T07:00:22.839103+00:00 app[worker.1]:   File "/app/userge/core/__init__.py", line 10, in <module>
2020-05-05T07:00:22.839271+00:00 app[worker.1]:     from ._database import get_collection
2020-05-05T07:00:22.839287+00:00 app[worker.1]:   File "/app/userge/core/_database/__init__.py", line 10, in <module>
2020-05-05T07:00:22.839441+00:00 app[worker.1]:     from .db import get_collection
2020-05-05T07:00:22.839457+00:00 app[worker.1]:   File "/app/userge/core/_database/db.py", line 23, in <module>
2020-05-05T07:00:22.839629+00:00 app[worker.1]:     if "Userge" in MGCLIENT.list_database_names():
2020-05-05T07:00:22.839647+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1909, in list_database_names
2020-05-05T07:00:22.840738+00:00 app[worker.1]:     for doc in self.list_databases(session, nameOnly=True)]
2020-05-05T07:00:22.840763+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1890, in list_databases
2020-05-05T07:00:22.841879+00:00 app[worker.1]:     res = admin._retryable_read_command(cmd, session=session)
2020-05-05T07:00:22.841897+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/database.py", line 748, in _retryable_read_command
2020-05-05T07:00:22.842389+00:00 app[worker.1]:     return self.__client._retryable_read(
2020-05-05T07:00:22.842414+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1453, in _retryable_read
2020-05-05T07:00:22.843297+00:00 app[worker.1]:     server = self._select_server(
2020-05-05T07:00:22.843320+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1253, in _select_server
2020-05-05T07:00:22.844095+00:00 app[worker.1]:     server = topology.select_server(server_selector)
2020-05-05T07:00:22.844112+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/topology.py", line 233, in select_server
2020-05-05T07:00:22.844386+00:00 app[worker.1]:     return random.choice(self.select_servers(selector,
2020-05-05T07:00:22.844402+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/topology.py", line 192, in select_servers
2020-05-05T07:00:22.844637+00:00 app[worker.1]:     server_descriptions = self._select_servers_loop(
2020-05-05T07:00:22.844660+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
2020-05-05T07:00:22.844901+00:00 app[worker.1]:     raise ServerSelectionTimeoutError(
2020-05-05T07:00:22.844976+00:00 app[worker.1]: pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed
2020-05-05T07:00:23.307268+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by K-E-N-W-A-Y** [comment]
double-check your MongoDB URL & password in that URL (make sure to remove < > part from URL). also, add 0.0.0.0/0 to MongoDB allowed IPs
