### ISSUE TITLE
skip if file size 0

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#33]
file: 
![resim](https://user-images.githubusercontent.com/63008918/83198613-352bc680-a148-11ea-9ae4-9bc44f6199b4.png)

on yandex, with no size. i think a empty file.

telegram: **File size equals to 0 B**
just skip this file and continue?
here is heroku log:

```
2020-05-28T20:42:45.751376+00:00 app[worker.1]: [28-May-20 20:42:45 - INFO] - root - Started 4 UpdatesWorkerTasks

2020-05-28T20:42:45.751779+00:00 app[worker.1]: [28-May-20 20:42:45 - INFO] - root - Started 4 DownloadWorkerTasks

2020-05-28T20:42:45.752236+00:00 app[worker.1]: [28-May-20 20:42:45 - INFO] - root - Started 4 UpdateWorkerTasks

2020-05-28T20:42:45.764514+00:00 app[worker.1]: [28-May-20 20:42:45 - INFO] - userge.core.client - <<<!  #####  Idling Userge  #####  !>>>

2020-05-28T20:43:02.830050+00:00 app[api]: Scaled to worker@0:Free by user xxx@xxx.xxx

2020-05-28T20:43:03.166797+00:00 heroku[worker.1]: State changed from up to down

2020-05-28T20:43:04.242397+00:00 heroku[worker.1]: Stopping all processes with SIGTERM

2020-05-28T20:43:04.284518+00:00 app[worker.1]: [28-May-20 20:43:04 - INFO] - root - Stop signal received (15). Exiting...

2020-05-28T20:43:04.355287+00:00 heroku[worker.1]: Process exited with status 143

2020-05-28T20:43:04.679991+00:00 app[api]: Scaled to worker@1:Free by user xxx@xxx.xxx

2020-05-28T20:43:18.290542+00:00 heroku[worker.1]: Starting process with command `bash run`

2020-05-28T20:43:18.896684+00:00 heroku[worker.1]: State changed from starting to up

2020-05-28T20:43:20.602894+00:00 app[worker.1]: [28-May-20 20:43:20 - INFO] - userge.config - Creating Download Path...

2020-05-28T20:43:20.603067+00:00 app[worker.1]: [28-May-20 20:43:20 - INFO] - userge.config - Checking Heroku App...

2020-05-28T20:43:20.988317+00:00 app[worker.1]: [28-May-20 20:43:20 - INFO] - userge.config - Heroku App : anpleron21 Found...

2020-05-28T20:43:20.988546+00:00 app[worker.1]: [28-May-20 20:43:20 - INFO] - userge.config - Cloning Heroku GIT...

2020-05-28T20:43:23.032905+00:00 app[worker.1]: [28-May-20 20:43:23 - INFO] - userge.config - Creating BIN...

2020-05-28T20:43:23.033080+00:00 app[worker.1]: [28-May-20 20:43:23 - INFO] - userge.config - Checking BINs...

2020-05-28T20:43:23.391900+00:00 app[worker.1]: [28-May-20 20:43:23 - INFO] - userge.core.database - $$$>>> Connecting to Database... <<<$$$

2020-05-28T20:43:24.259368+00:00 app[worker.1]: [28-May-20 20:43:24 - INFO] - userge.core.database - $$$>>> Userge Database Found :) => Now Logging to it... <<<$$$

2020-05-28T20:43:24.594598+00:00 app[worker.1]: [28-May-20 20:43:24 - INFO] - userge.core.client - <<<!  #####  Setting Userge Configs  #####  !>>>

2020-05-28T20:43:24.596281+00:00 app[worker.1]: [28-May-20 20:43:24 - INFO] - userge.core.client - <<<!  #####  Starting Userge  #####  !>>>

2020-05-28T20:43:24.883306+00:00 app[worker.1]: Pyrogram v0.17.1-async, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>

2020-05-28T20:43:24.883319+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

2020-05-28T20:43:24.883320+00:00 app[worker.1]: 

2020-05-28T20:43:25.000170+00:00 app[worker.1]: [28-May-20 20:43:24 - INFO] - root - NetWorkerTask started

2020-05-28T20:43:25.896860+00:00 app[worker.1]: [28-May-20 20:43:25 - INFO] - userge.core.client - <<<!  #####  Importing All Plugins  #####  !>>>

2020-05-28T20:43:28.878756+00:00 app[worker.1]: [28-May-20 20:43:28 - INFO] - userge.core.client - <<<!  #####  Imported (60) Plugins => ['userge.plugins.admin.gadmin', 'userge.plugins.admin.gban', 'userge.plugins.admin.locks', 'userge.plugins.fun.alive', 'userge.plugins.fun.autopic', 'userge.plugins.fun.carbon', 'userge.plugins.fun.convert', 'userge.plugins.fun.kang', 'userge.plugins.fun.memes', 'userge.plugins.fun.quote', 'userge.plugins.fun.type', 'userge.plugins.help', 'userge.plugins.misc.download', 'userge.plugins.misc.gdrive', 'userge.plugins.misc.pathlib', 'userge.plugins.misc.upload', 'userge.plugins.misc.utube', 'userge.plugins.tools.all', 'userge.plugins.tools.cancel', 'userge.plugins.tools.delete', 'userge.plugins.tools.ids', 'userge.plugins.tools.json', 'userge.plugins.tools.logs', 'userge.plugins.tools.manage', 'userge.plugins.tools.ping', 'userge.plugins.tools.repo', 'userge.plugins.tools.restart', 'userge.plugins.tools.sd', 'userge.plugins.tools.search', 'userge.plugins.tools.sleep', 'userge.plugins.tools.timeout', 'userge.plugins.tools.updater', 'userge.plugins.utils.admins', 'userge.plugins.utils.afk', 'userge.plugins.utils.covid', 'userge.plugins.utils.currency', 'userge.plugins.utils.dic', 'userge.plugins.utils.direct_links', 'userge.plugins.utils.dogbin', 'userge.plugins.utils.executor', 'userge.plugins.utils.filters', 'userge.plugins.utils.google', 'userge.plugins.utils.hash', 'userge.plugins.utils.header', 'userge.plugins.utils.notes', 'userge.plugins.utils.ocr', 'userge.plugins.utils.pmpermit', 'userge.plugins.utils.purge', 'userge.plugins.utils.removebg', 'userge.plugins.utils.speedtest', 'userge.plugins.utils.sudo', 'userge.plugins.utils.telegraph', 'userge.plugins.utils.thumbnail', 'userge.plugins.utils.translate', 'userge.plugins.utils.ud', 'userge.plugins.utils.weather', 'userge.plugins.utils.webss', 'userge.plugins.utils.welcome', 'userge.plugins.utils.whois', 'userge.plugins.utils.wikipedia']  #####  !>>>

2020-05-28T20:43:28.879037+00:00 app[worker.1]: [28-May-20 20:43:28 - INFO] - root - Started 4 UpdatesWorkerTasks

2020-05-28T20:43:28.879264+00:00 app[worker.1]: [28-May-20 20:43:28 - INFO] - root - Started 4 DownloadWorkerTasks

2020-05-28T20:43:28.879489+00:00 app[worker.1]: [28-May-20 20:43:28 - INFO] - root - Started 4 UpdateWorkerTasks

2020-05-28T20:43:28.885060+00:00 app[worker.1]: [28-May-20 20:43:28 - INFO] - userge.core.client - <<<!  #####  Idling Userge  #####  !>>>

2020-05-28T21:27:49.221574+00:00 app[worker.1]: [28-May-20 21:27:49 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:50.271044+00:00 app[worker.1]: [28-May-20 21:27:50 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:51.349329+00:00 app[worker.1]: [28-May-20 21:27:51 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:52.449874+00:00 app[worker.1]: [28-May-20 21:27:52 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:53.459854+00:00 app[worker.1]: [28-May-20 21:27:53 - WARNING] - pyrogram.session.session - [5] Retrying "messages.EditMessage" due to 

2020-05-28T21:27:53.460099+00:00 app[worker.1]: [28-May-20 21:27:53 - WARNING] - pyrogram.session.session - [5] Retrying "channels.GetMessages" due to 

2020-05-28T21:27:53.576900+00:00 app[worker.1]: [28-May-20 21:27:53 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:54.761598+00:00 app[worker.1]: [28-May-20 21:27:54 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:54.771437+00:00 app[worker.1]: [28-May-20 21:27:54 - ERROR] - pyrogram.client.ext.dispatcher - 

2020-05-28T21:27:54.771438+00:00 app[worker.1]: Traceback (most recent call last):

2020-05-28T21:27:54.771439+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 179, in update_worker

2020-05-28T21:27:54.771439+00:00 app[worker.1]:     await parser(update, users, chats)

2020-05-28T21:27:54.771440+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 77, in message_parser

2020-05-28T21:27:54.771440+00:00 app[worker.1]:     return await pyrogram.Message._parse(

2020-05-28T21:27:54.771443+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/types/messages_and_media/message.py", line 663, in _parse

2020-05-28T21:27:54.771443+00:00 app[worker.1]:     parsed_message.reply_to_message = await client.get_messages(

2020-05-28T21:27:54.771444+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/methods/messages/get_messages.py", line 115, in get_messages

2020-05-28T21:27:54.771444+00:00 app[worker.1]:     r = await self.send(rpc)

2020-05-28T21:27:54.771445+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/client.py", line 1419, in send

2020-05-28T21:27:54.771445+00:00 app[worker.1]:     r = await self.session.send(data, retries, timeout, self.sleep_threshold)

2020-05-28T21:27:54.771446+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 449, in send

2020-05-28T21:27:54.771446+00:00 app[worker.1]:     return await self.send(data, retries - 1, timeout)

2020-05-28T21:27:54.771447+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 449, in send

2020-05-28T21:27:54.771447+00:00 app[worker.1]:     return await self.send(data, retries - 1, timeout)

2020-05-28T21:27:54.771447+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 449, in send

2020-05-28T21:27:54.771448+00:00 app[worker.1]:     return await self.send(data, retries - 1, timeout)

2020-05-28T21:27:54.771448+00:00 app[worker.1]:   [Previous line repeated 2 more times]

2020-05-28T21:27:54.771449+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 440, in send

2020-05-28T21:27:54.771449+00:00 app[worker.1]:     raise e from None

2020-05-28T21:27:54.771449+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 427, in send

2020-05-28T21:27:54.771450+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)

2020-05-28T21:27:54.771450+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 381, in _send

2020-05-28T21:27:54.771451+00:00 app[worker.1]:     raise e

2020-05-28T21:27:54.771451+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 378, in _send

2020-05-28T21:27:54.771452+00:00 app[worker.1]:     await self.connection.send(payload)

2020-05-28T21:27:54.771452+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/connection/connection.py", line 80, in send

2020-05-28T21:27:54.771452+00:00 app[worker.1]:     raise OSError

2020-05-28T21:27:54.771453+00:00 app[worker.1]: OSError

2020-05-28T21:27:54.840842+00:00 app[worker.1]: [28-May-20 21:27:54 - WARNING] - pyrogram.session.session - [5] Retrying "channels.GetMessages" due to 

2020-05-28T21:27:55.557255+00:00 app[worker.1]: [28-May-20 21:27:55 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:56.262299+00:00 app[worker.1]: [28-May-20 21:27:56 - INFO] - root - NetWorkerTask started

2020-05-28T21:27:56.864497+00:00 app[worker.1]: [28-May-20 21:27:56 - INFO] - root - NetWorkerTask started

2020-05-28T21:33:08.107617+00:00 app[worker.1]: [28-May-20 21:33:08 - INFO] - root - NetWorkerTask started

2020-05-28T21:41:19.808768+00:00 app[worker.1]: [28-May-20 21:41:19 - INFO] - root - NetWorkerTask started
```

**Comment by rking32** [comment]
which command did you use ?
`.upload` ?

**Comment by qorcfotian** [comment]
@rking32 yes
.upload directoryA

**Comment by rking32** [comment]
@qorcfotian can you check it now

**Comment by qorcfotian** [comment]
you're the best. thank you for all :)
