### ISSUE TITLE
upload interrupted

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#41]
in telegram, bot says: `[520 Unknown error]: [-503 Timeout] (caused by "messages.SendMedia")`
```
USERGE LOGS :

[03-Jun-20 02:25:53 - ERROR] - pyrogram.client.ext.dispatcher - [520 Unknown error]: [-503 Timeout] (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 204, in update_worker
    await handler.callback(self.client, *args)
  File "/app/userge/core/methods/decorators.py", line 159, in template
    await func(Message(_, __, **kwargs))
  File "/app/userge/plugins/misc/upload.py", line 177, in uploadtotg
    await explorer(string, message.chat.id, flags, del_path)
  File "/app/userge/plugins/misc/upload.py", line 189, in explorer
    await explorer(i, chatid, flags, del_path)
  File "/app/userge/plugins/misc/upload.py", line 189, in explorer
    await explorer(i, chatid, flags, del_path)
  File "/app/userge/plugins/misc/upload.py", line 184, in explorer
    await upload(path, chatid, flags, del_path)
  File "/app/userge/plugins/misc/upload.py", line 198, in upload
    await doc_upload(chat_id, path, del_path)
  File "/app/userge/plugins/misc/upload.py", line 223, in doc_upload
    raise u_e
  File "/app/userge/plugins/misc/upload.py", line 209, in doc_upload
    msg = await userge.send_document(
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/methods/messages/send_document.py", line 166, in send_document
    r = await self.send(
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/client.py", line 1419, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
    return await self._send(data, timeout=timeout)
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 399, in _send
    RPCError.raise_it(result, type(data))
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 60, in raise_it
    raise UnknownError(
pyrogram.errors.rpc_error.UnknownError: [520 Unknown error]: [-503 Timeout] (caused by "messages.SendMedia")
[03-Jun-20 06:42:16 - ERROR] - pyrogram.client.ext.dispatcher - [400 MESSAGE_EMPTY]: The message sent is empty (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 204, in update_worker
    await handler.callback(self.client, *args)
  File "/app/userge/core/methods/decorators.py", line 159, in template
    await func(Message(_, __, **kwargs))
  File "/app/userge/plugins/utils/executor.py", line 83, in exec_
    await message.edit_or_send_as_file(text=output,
  File "/app/userge/core/methods/message.py", line 639, in edit_or_send_as_file
    return await self.edit(text=text,
  File "/app/userge/core/methods/message.py", line 309, in edit
    msg_ = await self._client.edit_message_text(
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/client.py", line 1419, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
    return await self._send(data, timeout=timeout)
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 399, in _send
    RPCError.raise_it(result, type(data))
  File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 79, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageEmpty: [400 MESSAGE_EMPTY]: The message sent is empty (caused by "messages.EditMessage")
[03-Jun-20 06:42:27 - INFO] - root - NetWorkerTask started
```

**Comment by rking32** [comment]
can you explain this more ?

**Comment by qorcfotian** [comment]
@rking32 in last vrsions, no any problem. you may dismiss this issue ;)
