### ISSUE TITLE
Error Deleting Help message

### ISSUE THREAD

**Issue by ZekXtreme** [UsergeTeam/Userge#518]
logger : #TRACEBACK

PLUGIN : userge.plugins.builtin.help.__main__
FUNCTION : helpme
ERROR : 'Message' object has no attribute '_client'

Traceback (most recent call last):
  File "/app/userge/core/methods/decorators/raw_decorator.py", line 341, in template
    await func(types.bound.Message.parse(
  File "/app/userge/plugins/builtin/help/__main__.py", line 112, in helpme
    await message.edit(out_str,
  File "/app/userge/core/types/bound/message.py", line 456, in edit
    return await self._client.edit_message_text(
  File "/app/userge/core/methods/messages/edit_message_text.py", line 101, in edit_message_text
    return bool(await msg.delete())
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 3186, in delete
    return await self._client.delete_messages(
AttributeError: 'Message' object has no attribute '_client'

**Comment by jigarvarma2k20** [comment]
Updated to latest version??

**Comment by ZekXtreme** [comment]
yes 
![image](https://user-images.githubusercontent.com/83297638/176804046-99dd1d8d-a466-4d8c-b80a-511fc126212a.png)
