### ISSUE TITLE
No respond from bot

### ISSUE THREAD

**Issue by 0x8mx** [UsergeTeam/Userge#59]
Hello guys,

i setup Userge as described on heroku. The Bot worked for ~30sec after that it doesn't work anymore. Any help is appreciated. 
This is the output from heroku log:

2020-06-13T10:29:01.474464+00:00 heroku[worker.1]: Starting process with command `bash run`

2020-06-13T10:29:02.120267+00:00 heroku[worker.1]: State changed from starting to up

2020-06-13T10:29:04.370341+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Creating Download Path...

2020-06-13T10:29:04.370513+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Checking Heroku App...

2020-06-13T10:29:04.814888+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Heroku App : userge-new Found...

2020-06-13T10:29:04.815209+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Cloning Heroku GIT...

2020-06-13T10:29:05.564459+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.config - Creating BIN...

2020-06-13T10:29:05.564738+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.config - Checking BINs...

2020-06-13T10:29:05.910793+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.core.database - $$$>>> Connecting to Database... <<<$$$

2020-06-13T10:29:06.293865+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.database - $$$>>> Userge Database Not Found :( => Creating New Database... <<<$$$

2020-06-13T10:29:06.443200+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.client - <<<!  #####  Setting Userge Configs  #####  !>>>

2020-06-13T10:29:06.444969+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.client - <<<!  #####  Starting Userge  #####  !>>>

2020-06-13T10:29:06.813966+00:00 app[worker.1]: Pyrogram v0.17.1-async, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>

2020-06-13T10:29:06.813978+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

2020-06-13T10:29:06.813979+00:00 app[worker.1]: 

2020-06-13T10:29:06.926642+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - root - NetWorkerTask started

2020-06-13T10:29:07.582285+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 UpdatesWorkerTasks

2020-06-13T10:29:07.582768+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 DownloadWorkerTasks

2020-06-13T10:29:07.583513+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 UpdateWorkerTasks

2020-06-13T10:29:07.586681+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - userge.core.client - <<<!  #####  Importing All Plugins  #####  !>>>

2020-06-13T10:29:09.199957+00:00 app[worker.1]: [13-Jun-20 10:29:09 - INFO] - userge.core.client - <<<!  #####  Imported (60) Plugins => ['userge.plugins.admin.gadmin', 'userge.plugins.admin.gban', 'userge.plugins.admin.locks', 'userge.plugins.fun.alive', 'userge.plugins.fun.autopic', 'userge.plugins.fun.carbon', 'userge.plugins.fun.convert', 'userge.plugins.fun.kang', 'userge.plugins.fun.memes', 'userge.plugins.fun.quote', 'userge.plugins.fun.type', 'userge.plugins.help', 'userge.plugins.misc.download', 'userge.plugins.misc.gdrive', 'userge.plugins.misc.pathlib', 'userge.plugins.misc.upload', 'userge.plugins.misc.utube', 'userge.plugins.tools.all', 'userge.plugins.tools.cancel', 'userge.plugins.tools.delete', 'userge.plugins.tools.ids', 'userge.plugins.tools.json', 'userge.plugins.tools.logs', 'userge.plugins.tools.manage', 'userge.plugins.tools.ping', 'userge.plugins.tools.repo', 'userge.plugins.tools.restart', 'userge.plugins.tools.sd', 'userge.plugins.tools.search', 'userge.plugins.tools.sleep', 'userge.plugins.tools.timeout', 'userge.plugins.tools.updater', 'userge.plugins.utils.admins', 'userge.plugins.utils.afk', 'userge.plugins.utils.covid', 'userge.plugins.utils.currency', 'userge.plugins.utils.dic', 'userge.plugins.utils.direct_links', 'userge.plugins.utils.dogbin', 'userge.plugins.utils.executor', 'userge.plugins.utils.filters', 'userge.plugins.utils.google', 'userge.plugins.utils.hash', 'userge.plugins.utils.header', 'userge.plugins.utils.notes', 'userge.plugins.utils.ocr', 'userge.plugins.utils.pmpermit', 'userge.plugins.utils.purge', 'userge.plugins.utils.removebg', 'userge.plugins.utils.speedtest', 'userge.plugins.utils.sudo', 'userge.plugins.utils.telegraph', 'userge.plugins.utils.thumbnail', 'userge.plugins.utils.translate', 'userge.plugins.utils.ud', 'userge.plugins.utils.weather', 'userge.plugins.utils.webss', 'userge.plugins.utils.welcome', 'userge.plugins.utils.whois', 'userge.plugins.utils.wikipedia']  #####  !>>>

2020-06-13T10:29:09.200317+00:00 app[worker.1]: [13-Jun-20 10:29:09 - INFO] - userge.core.client - <<<!  #####  Idling Userge  #####  !>>>

**Comment by Harsh-br0** [comment]
> Hello guys,
> 
> i setup Userge as described on heroku. The Bot worked for ~30sec after that it doesn't work anymore. Any help is appreciated.
> This is the output from heroku log:
> 
> 2020-06-13T10:29:01.474464+00:00 heroku[worker.1]: Starting process with command `bash run`
> 
> 2020-06-13T10:29:02.120267+00:00 heroku[worker.1]: State changed from starting to up
> 
> 2020-06-13T10:29:04.370341+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Creating Download Path...
> 
> 2020-06-13T10:29:04.370513+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Checking Heroku App...
> 
> 2020-06-13T10:29:04.814888+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Heroku App : userge-new Found...
> 
> 2020-06-13T10:29:04.815209+00:00 app[worker.1]: [13-Jun-20 10:29:04 - INFO] - userge.config - Cloning Heroku GIT...
> 
> 2020-06-13T10:29:05.564459+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.config - Creating BIN...
> 
> 2020-06-13T10:29:05.564738+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.config - Checking BINs...
> 
> 2020-06-13T10:29:05.910793+00:00 app[worker.1]: [13-Jun-20 10:29:05 - INFO] - userge.core.database - $$$>>> Connecting to Database... <<<$$$
> 
> 2020-06-13T10:29:06.293865+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.database - $$$>>> Userge Database Not Found :( => Creating New Database... <<<$$$
> 
> 2020-06-13T10:29:06.443200+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.client - <<<! ##### Setting Userge Configs ##### !>>>
> 
> 2020-06-13T10:29:06.444969+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - userge.core.client - <<<! ##### Starting Userge ##### !>>>
> 
> 2020-06-13T10:29:06.813966+00:00 app[worker.1]: Pyrogram v0.17.1-async, Copyright (C) 2017-2020 Dan https://github.com/delivrance
> 
> 2020-06-13T10:29:06.813978+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
> 
> 2020-06-13T10:29:06.813979+00:00 app[worker.1]:
> 
> 2020-06-13T10:29:06.926642+00:00 app[worker.1]: [13-Jun-20 10:29:06 - INFO] - root - NetWorkerTask started
> 
> 2020-06-13T10:29:07.582285+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 UpdatesWorkerTasks
> 
> 2020-06-13T10:29:07.582768+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 DownloadWorkerTasks
> 
> 2020-06-13T10:29:07.583513+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - root - Started 4 UpdateWorkerTasks
> 
> 2020-06-13T10:29:07.586681+00:00 app[worker.1]: [13-Jun-20 10:29:07 - INFO] - userge.core.client - <<<! ##### Importing All Plugins ##### !>>>
> 
> 2020-06-13T10:29:09.199957+00:00 app[worker.1]: [13-Jun-20 10:29:09 - INFO] - userge.core.client - <<<! ##### Imported (60) Plugins => ['userge.plugins.admin.gadmin', 'userge.plugins.admin.gban', 'userge.plugins.admin.locks', 'userge.plugins.fun.alive', 'userge.plugins.fun.autopic', 'userge.plugins.fun.carbon', 'userge.plugins.fun.convert', 'userge.plugins.fun.kang', 'userge.plugins.fun.memes', 'userge.plugins.fun.quote', 'userge.plugins.fun.type', 'userge.plugins.help', 'userge.plugins.misc.download', 'userge.plugins.misc.gdrive', 'userge.plugins.misc.pathlib', 'userge.plugins.misc.upload', 'userge.plugins.misc.utube', 'userge.plugins.tools.all', 'userge.plugins.tools.cancel', 'userge.plugins.tools.delete', 'userge.plugins.tools.ids', 'userge.plugins.tools.json', 'userge.plugins.tools.logs', 'userge.plugins.tools.manage', 'userge.plugins.tools.ping', 'userge.plugins.tools.repo', 'userge.plugins.tools.restart', 'userge.plugins.tools.sd', 'userge.plugins.tools.search', 'userge.plugins.tools.sleep', 'userge.plugins.tools.timeout', 'userge.plugins.tools.updater', 'userge.plugins.utils.admins', 'userge.plugins.utils.afk', 'userge.plugins.utils.covid', 'userge.plugins.utils.currency', 'userge.plugins.utils.dic', 'userge.plugins.utils.direct_links', 'userge.plugins.utils.dogbin', 'userge.plugins.utils.executor', 'userge.plugins.utils.filters', 'userge.plugins.utils.google', 'userge.plugins.utils.hash', 'userge.plugins.utils.header', 'userge.plugins.utils.notes', 'userge.plugins.utils.ocr', 'userge.plugins.utils.pmpermit', 'userge.plugins.utils.purge', 'userge.plugins.utils.removebg', 'userge.plugins.utils.speedtest', 'userge.plugins.utils.sudo', 'userge.plugins.utils.telegraph', 'userge.plugins.utils.thumbnail', 'userge.plugins.utils.translate', 'userge.plugins.utils.ud', 'userge.plugins.utils.weather', 'userge.plugins.utils.webss', 'userge.plugins.utils.welcome', 'userge.plugins.utils.whois', 'userge.plugins.utils.wikipedia'] ##### !>>>
> 
> 2020-06-13T10:29:09.200317+00:00 app[worker.1]: [13-Jun-20 10:29:09 - INFO] - userge.core.client - <<<! ##### Idling Userge ##### !>>>

Logs saying its done👀

**Comment by rking32** [comment]
@0x8mx if you add `CMD_TRIGGER` to heroku vars first remove it

**Comment by 0x8mx** [comment]
> 
> 
> @0x8mx if you add `CMD_TRIGGER` to heroku vars first remove it

@rking32 thanks for your answer. I tried your solution, sadly it doesn't work. I have reinstalled the repo on heroku same problem again. 

I tried setup the bot on my server, there i get the following error for "bash run":

  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/liitri/bots/Userge/userge/__init__.py", line 10, in <module>
    from userge.config import Config, get_version
  File "/home/liitri/bots/Userge/userge/config.py", line 43, in <module>
    class Config:
  File "/home/liitri/bots/Userge/userge/config.py", line 66, in Config
    LOG_CHANNEL_ID = int(os.environ.get("LOG_CHANNEL_ID", 0))
ValueError: invalid literal for int() with base 10: ''

**Comment by Phyco-Ninja** [comment]
> > @0x8mx if you add `CMD_TRIGGER` to heroku vars first remove it
> 
> @rking32 thanks for your answer. I tried your solution, sadly it doesn't work. I have reinstalled the repo on heroku same problem again.
> 
> I tried setup the bot on my server, there i get the following error for "bash run":
> 
> [13-Jun-20 17:51:52 - INFO] - userge.config - config.env Found and loading ...
> Traceback (most recent call last):
> File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
> mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
> return _get_module_details(pkg_main_name, error)
> File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
> **import**(pkg_name)
> File "/home/liitri/bots/Userge/userge/**init**.py", line 10, in
> from userge.config import Config, get_version
> File "/home/liitri/bots/Userge/userge/config.py", line 43, in
> class Config:
> File "/home/liitri/bots/Userge/userge/config.py", line 66, in Config
> LOG_CHANNEL_ID = int(os.environ.get("LOG_CHANNEL_ID", 0))
> ValueError: invalid literal for int() with base 10: ''

What did u enter in Log channel id? Seems it's not an integer value

**Comment by 0x8mx** [comment]
Thanks for your help. i leaved it blank. i filled now the channel ID. It worked somehow, but now i get the following error message :( , soory for my inconvenience.

[13-Jun-20 18:07:22 - INFO] - userge.config - config.env Found and loading ...
[13-Jun-20 18:07:22 - INFO] - userge.config - Checking REPO...
[13-Jun-20 18:07:22 - ERROR] - userge.config - Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v upstream
  stderr: 'fatal: no path specified; see 'git help pull' for valid url syntax'

**Comment by Akshaygit1** [comment]
> Thanks for your help. i leaved it blank. i filled now the channel ID. It worked somehow, but now i get the following error message :( , soory for my inconvenience.
> 
> [13-Jun-20 18:07:22 - INFO] - userge.config - config.env Found and loading ...
> [13-Jun-20 18:07:22 - INFO] - userge.config - Checking REPO...
> [13-Jun-20 18:07:22 - ERROR] - userge.config - Cmd('git') failed due to: exit code(128)
> cmdline: git fetch -v upstream
> stderr: 'fatal: no path specified; see 'git help pull' for valid url syntax'

https://github.com/UsergeTeam/Userge/issues/51#issuecomment-641200807

**Comment by 0x8mx** [comment]
> 
> 
> > Thanks for your help. i leaved it blank. i filled now the channel ID. It worked somehow, but now i get the following error message :( , soory for my inconvenience.
> > [13-Jun-20 18:07:22 - INFO] - userge.config - config.env Found and loading ...
> > [13-Jun-20 18:07:22 - INFO] - userge.config - Checking REPO...
> > [13-Jun-20 18:07:22 - ERROR] - userge.config - Cmd('git') failed due to: exit code(128)
> > cmdline: git fetch -v upstream
> > stderr: 'fatal: no path specified; see 'git help pull' for valid url syntax'
> 
> [#51 (comment)](https://github.com/UsergeTeam/Userge/issues/51#issuecomment-641200807)

Thank you!!!!! The bot is now successfully running, but same issue as on heroku plattform. No response from bot. For example no ping feedback after the command .ping

**Comment by rking32** [comment]
@0x8mx no errors in heroku logs ?

**Comment by 0x8mx** [comment]
> 
> 
> @0x8mx no errors in heroku logs ?

It works now!! I generated a new session string, after that the bot works flawless. Thanks for all your fast help :)
